#-------------------------------------------------------------------------------
# aliases
#-------------------------------------------------------------------------------
alias h='history -99'


#-------------------------------------------------------------------------------
# color aliases
#-------------------------------------------------------------------------------
alias ls='ls --color=auto'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color'


#-------------------------------------------------------------------------------
# add local dirs to path
#-------------------------------------------------------------------------------
PATH="$HOME:/home/pi/patcher/lib/os:$PATH"


#-------------------------------------------------------------------------------
# use nano
#-------------------------------------------------------------------------------
export EDITOR=nano
# bindkey -e # use emacs keybindings in vi


#-------------------------------------------------------------------------------
# history
#-------------------------------------------------------------------------------
setopt histignorealldups sharehistory incappendhistory
HISTSIZE=100
SAVEHIST=100
HISTFILE=~/.zsh_history


#-------------------------------------------------------------------------------
# prompt
#-------------------------------------------------------------------------------
# autoload -Uz promptinit
# promptinit
# prompt adam1
if [[ -t 0 ]]; then
    export PROMPT='%B%F{009}•%f %F{015}%m : %~%f %F{011}%#%f%b '
    # root
    if (( $EUID == 0 )); then
        export PROMPT='%B%F{009}•%f %F{015}%m : %~%f %F{009}%#%f%b '
        force_color_prompt=yes
    fi
fi


#-------------------------------------------------------------------------------
# gcc colors
# https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Language-Independent-Options.html
#--------------------------------
export GCC_COLORS='error=01;31:warning=01;33:note=01;36:caret=01;31:locus=01;37:quote=01;37'


#-------------------------------------------------------------------------------
# Use modern completion system
#-------------------------------------------------------------------------------
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


#-------------------------------------------------------------------------------
# eof
#-------------------------------------------------------------------------------
